title: Shaw
description: You were my safe place.
google_analytics: G-43FGY9WSHQ
theme: jekyll-theme-cayman
show_urls: true
github:
  root_url: https://www.imdb.com/title/tt1839578/characters/nm0009918
  shaw_url: https://www.imdb.com/title/tt1839578/characters/nm1083404
  description: But when things got to be too bad<br>There was one place I would go to in my mind<br>Here<br>With you<br>You were my safe place